/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as NbRouteRouteImport } from './routes/nb/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as NbIndexRouteImport } from './routes/nb/index'
import { Route as NbDashboardRouteImport } from './routes/nb/dashboard'
import { Route as NbMarketRouteImport } from './routes/nb/market'
import { Route as NbNftRouteImport } from './routes/nb/nft'
import { Route as NbProfileRouteImport } from './routes/nb/profile'
import { Route as NbTrenchesRouteImport } from './routes/nb/trenches'
import { Route as NbTrendingRouteImport } from './routes/nb/trending'
import { Route as NbWalletRouteImport } from './routes/nb/wallet'
import { Route as AuthenticatedMarketIndexRouteImport } from './routes/_authenticated/market/index'
import { Route as AuthenticatedNftIndexRouteImport } from './routes/_authenticated/nft/index'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedTokenTokenAddressRouteImport } from './routes/_authenticated/token/$tokenAddress'
import { Route as AuthenticatedTrenchesIndexRouteImport } from './routes/_authenticated/trenches/index'
import { Route as AuthenticatedTrendingIndexRouteImport } from './routes/_authenticated/trending/index'
import { Route as AuthenticatedWalletIndexRouteImport } from './routes/_authenticated/wallet/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const NbRouteRoute = NbRouteRouteImport.update({
  id: '/nb',
  path: '/nb',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const NbIndexRoute = NbIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NbRouteRoute,
} as any)
const NbDashboardRoute = NbDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => NbRouteRoute,
} as any)
const NbMarketRoute = NbMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => NbRouteRoute,
} as any)
const NbNftRoute = NbNftRouteImport.update({
  id: '/nft',
  path: '/nft',
  getParentRoute: () => NbRouteRoute,
} as any)
const NbProfileRoute = NbProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => NbRouteRoute,
} as any)
const NbTrenchesRoute = NbTrenchesRouteImport.update({
  id: '/trenches',
  path: '/trenches',
  getParentRoute: () => NbRouteRoute,
} as any)
const NbTrendingRoute = NbTrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => NbRouteRoute,
} as any)
const NbWalletRoute = NbWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => NbRouteRoute,
} as any)
const AuthenticatedMarketIndexRoute =
  AuthenticatedMarketIndexRouteImport.update({
    id: '/market/',
    path: '/market/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNftIndexRoute = AuthenticatedNftIndexRouteImport.update({
  id: '/nft/',
  path: '/nft/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTokenTokenAddressRoute =
  AuthenticatedTokenTokenAddressRouteImport.update({
    id: '/token/$tokenAddress',
    path: '/token/$tokenAddress',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrenchesIndexRoute =
  AuthenticatedTrenchesIndexRouteImport.update({
    id: '/trenches/',
    path: '/trenches/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrendingIndexRoute =
  AuthenticatedTrendingIndexRouteImport.update({
    id: '/trending/',
    path: '/trending/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWalletIndexRoute =
  AuthenticatedWalletIndexRouteImport.update({
    id: '/wallet/',
    path: '/wallet/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/nb': typeof NbRouteRouteWithChildren
  '/nb/dashboard': typeof NbDashboardRoute
  '/nb/market': typeof NbMarketRoute
  '/nb/nft': typeof NbNftRoute
  '/nb/profile': typeof NbProfileRoute
  '/nb/trenches': typeof NbTrenchesRoute
  '/nb/trending': typeof NbTrendingRoute
  '/nb/wallet': typeof NbWalletRoute
  '/nb/': typeof NbIndexRoute
  '/token/$tokenAddress': typeof AuthenticatedTokenTokenAddressRoute
  '/market/': typeof AuthenticatedMarketIndexRoute
  '/nft/': typeof AuthenticatedNftIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/trenches/': typeof AuthenticatedTrenchesIndexRoute
  '/trending/': typeof AuthenticatedTrendingIndexRoute
  '/wallet/': typeof AuthenticatedWalletIndexRoute
}
export interface FileRoutesByTo {
  '/nb/dashboard': typeof NbDashboardRoute
  '/nb/market': typeof NbMarketRoute
  '/nb/nft': typeof NbNftRoute
  '/nb/profile': typeof NbProfileRoute
  '/nb/trenches': typeof NbTrenchesRoute
  '/nb/trending': typeof NbTrendingRoute
  '/nb/wallet': typeof NbWalletRoute
  '/': typeof AuthenticatedIndexRoute
  '/nb': typeof NbIndexRoute
  '/token/$tokenAddress': typeof AuthenticatedTokenTokenAddressRoute
  '/market': typeof AuthenticatedMarketIndexRoute
  '/nft': typeof AuthenticatedNftIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/trenches': typeof AuthenticatedTrenchesIndexRoute
  '/trending': typeof AuthenticatedTrendingIndexRoute
  '/wallet': typeof AuthenticatedWalletIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/nb': typeof NbRouteRouteWithChildren
  '/nb/dashboard': typeof NbDashboardRoute
  '/nb/market': typeof NbMarketRoute
  '/nb/nft': typeof NbNftRoute
  '/nb/profile': typeof NbProfileRoute
  '/nb/trenches': typeof NbTrenchesRoute
  '/nb/trending': typeof NbTrendingRoute
  '/nb/wallet': typeof NbWalletRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/nb/': typeof NbIndexRoute
  '/_authenticated/token/$tokenAddress': typeof AuthenticatedTokenTokenAddressRoute
  '/_authenticated/market/': typeof AuthenticatedMarketIndexRoute
  '/_authenticated/nft/': typeof AuthenticatedNftIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/trenches/': typeof AuthenticatedTrenchesIndexRoute
  '/_authenticated/trending/': typeof AuthenticatedTrendingIndexRoute
  '/_authenticated/wallet/': typeof AuthenticatedWalletIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/nb'
    | '/nb/dashboard'
    | '/nb/market'
    | '/nb/nft'
    | '/nb/profile'
    | '/nb/trenches'
    | '/nb/trending'
    | '/nb/wallet'
    | '/nb/'
    | '/token/$tokenAddress'
    | '/market/'
    | '/nft/'
    | '/profile/'
    | '/trenches/'
    | '/trending/'
    | '/wallet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/nb/dashboard'
    | '/nb/market'
    | '/nb/nft'
    | '/nb/profile'
    | '/nb/trenches'
    | '/nb/trending'
    | '/nb/wallet'
    | '/'
    | '/nb'
    | '/token/$tokenAddress'
    | '/market'
    | '/nft'
    | '/profile'
    | '/trenches'
    | '/trending'
    | '/wallet'
  id:
    | '__root__'
    | '/_authenticated'
    | '/nb'
    | '/nb/dashboard'
    | '/nb/market'
    | '/nb/nft'
    | '/nb/profile'
    | '/nb/trenches'
    | '/nb/trending'
    | '/nb/wallet'
    | '/_authenticated/'
    | '/nb/'
    | '/_authenticated/token/$tokenAddress'
    | '/_authenticated/market/'
    | '/_authenticated/nft/'
    | '/_authenticated/profile/'
    | '/_authenticated/trenches/'
    | '/_authenticated/trending/'
    | '/_authenticated/wallet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  NbRouteRoute: typeof NbRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nb': {
      id: '/nb'
      path: '/nb'
      fullPath: '/nb'
      preLoaderRoute: typeof NbRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/nb/': {
      id: '/nb/'
      path: '/'
      fullPath: '/nb/'
      preLoaderRoute: typeof NbIndexRouteImport
      parentRoute: typeof NbRouteRoute
    }
    '/nb/dashboard': {
      id: '/nb/dashboard'
      path: '/dashboard'
      fullPath: '/nb/dashboard'
      preLoaderRoute: typeof NbDashboardRouteImport
      parentRoute: typeof NbRouteRoute
    }
    '/nb/market': {
      id: '/nb/market'
      path: '/market'
      fullPath: '/nb/market'
      preLoaderRoute: typeof NbMarketRouteImport
      parentRoute: typeof NbRouteRoute
    }
    '/nb/nft': {
      id: '/nb/nft'
      path: '/nft'
      fullPath: '/nb/nft'
      preLoaderRoute: typeof NbNftRouteImport
      parentRoute: typeof NbRouteRoute
    }
    '/nb/profile': {
      id: '/nb/profile'
      path: '/profile'
      fullPath: '/nb/profile'
      preLoaderRoute: typeof NbProfileRouteImport
      parentRoute: typeof NbRouteRoute
    }
    '/nb/trenches': {
      id: '/nb/trenches'
      path: '/trenches'
      fullPath: '/nb/trenches'
      preLoaderRoute: typeof NbTrenchesRouteImport
      parentRoute: typeof NbRouteRoute
    }
    '/nb/trending': {
      id: '/nb/trending'
      path: '/trending'
      fullPath: '/nb/trending'
      preLoaderRoute: typeof NbTrendingRouteImport
      parentRoute: typeof NbRouteRoute
    }
    '/nb/wallet': {
      id: '/nb/wallet'
      path: '/wallet'
      fullPath: '/nb/wallet'
      preLoaderRoute: typeof NbWalletRouteImport
      parentRoute: typeof NbRouteRoute
    }
    '/_authenticated/market/': {
      id: '/_authenticated/market/'
      path: '/market'
      fullPath: '/market/'
      preLoaderRoute: typeof AuthenticatedMarketIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nft/': {
      id: '/_authenticated/nft/'
      path: '/nft'
      fullPath: '/nft/'
      preLoaderRoute: typeof AuthenticatedNftIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/token/$tokenAddress': {
      id: '/_authenticated/token/$tokenAddress'
      path: '/token/$tokenAddress'
      fullPath: '/token/$tokenAddress'
      preLoaderRoute: typeof AuthenticatedTokenTokenAddressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trenches/': {
      id: '/_authenticated/trenches/'
      path: '/trenches'
      fullPath: '/trenches/'
      preLoaderRoute: typeof AuthenticatedTrenchesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trending/': {
      id: '/_authenticated/trending/'
      path: '/trending'
      fullPath: '/trending/'
      preLoaderRoute: typeof AuthenticatedTrendingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet/': {
      id: '/_authenticated/wallet/'
      path: '/wallet'
      fullPath: '/wallet/'
      preLoaderRoute: typeof AuthenticatedWalletIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedTokenTokenAddressRoute: typeof AuthenticatedTokenTokenAddressRoute
  AuthenticatedMarketIndexRoute: typeof AuthenticatedMarketIndexRoute
  AuthenticatedNftIndexRoute: typeof AuthenticatedNftIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedTrenchesIndexRoute: typeof AuthenticatedTrenchesIndexRoute
  AuthenticatedTrendingIndexRoute: typeof AuthenticatedTrendingIndexRoute
  AuthenticatedWalletIndexRoute: typeof AuthenticatedWalletIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedTokenTokenAddressRoute: AuthenticatedTokenTokenAddressRoute,
  AuthenticatedMarketIndexRoute: AuthenticatedMarketIndexRoute,
  AuthenticatedNftIndexRoute: AuthenticatedNftIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedTrenchesIndexRoute: AuthenticatedTrenchesIndexRoute,
  AuthenticatedTrendingIndexRoute: AuthenticatedTrendingIndexRoute,
  AuthenticatedWalletIndexRoute: AuthenticatedWalletIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface NbRouteRouteChildren {
  NbDashboardRoute: typeof NbDashboardRoute
  NbMarketRoute: typeof NbMarketRoute
  NbNftRoute: typeof NbNftRoute
  NbProfileRoute: typeof NbProfileRoute
  NbTrenchesRoute: typeof NbTrenchesRoute
  NbTrendingRoute: typeof NbTrendingRoute
  NbWalletRoute: typeof NbWalletRoute
  NbIndexRoute: typeof NbIndexRoute
}

const NbRouteRouteChildren: NbRouteRouteChildren = {
  NbDashboardRoute: NbDashboardRoute,
  NbMarketRoute: NbMarketRoute,
  NbNftRoute: NbNftRoute,
  NbProfileRoute: NbProfileRoute,
  NbTrenchesRoute: NbTrenchesRoute,
  NbTrendingRoute: NbTrendingRoute,
  NbWalletRoute: NbWalletRoute,
  NbIndexRoute: NbIndexRoute,
}

const NbRouteRouteWithChildren =
  NbRouteRoute._addFileChildren(NbRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  NbRouteRoute: NbRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
