/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedMarketIndexRouteImport } from './routes/_authenticated/market/index'
import { Route as AuthenticatedNftIndexRouteImport } from './routes/_authenticated/nft/index'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedTokenTokenAddressRouteImport } from './routes/_authenticated/token/$tokenAddress'
import { Route as AuthenticatedTrenchesIndexRouteImport } from './routes/_authenticated/trenches/index'
import { Route as AuthenticatedTrendingIndexRouteImport } from './routes/_authenticated/trending/index'
import { Route as AuthenticatedWalletIndexRouteImport } from './routes/_authenticated/wallet/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketIndexRoute =
  AuthenticatedMarketIndexRouteImport.update({
    id: '/market/',
    path: '/market/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNftIndexRoute = AuthenticatedNftIndexRouteImport.update({
  id: '/nft/',
  path: '/nft/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTokenTokenAddressRoute =
  AuthenticatedTokenTokenAddressRouteImport.update({
    id: '/token/$tokenAddress',
    path: '/token/$tokenAddress',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrenchesIndexRoute =
  AuthenticatedTrenchesIndexRouteImport.update({
    id: '/trenches/',
    path: '/trenches/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrendingIndexRoute =
  AuthenticatedTrendingIndexRouteImport.update({
    id: '/trending/',
    path: '/trending/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWalletIndexRoute =
  AuthenticatedWalletIndexRouteImport.update({
    id: '/wallet/',
    path: '/wallet/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/token/$tokenAddress': typeof AuthenticatedTokenTokenAddressRoute
  '/market/': typeof AuthenticatedMarketIndexRoute
  '/nft/': typeof AuthenticatedNftIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/trenches/': typeof AuthenticatedTrenchesIndexRoute
  '/trending/': typeof AuthenticatedTrendingIndexRoute
  '/wallet/': typeof AuthenticatedWalletIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/token/$tokenAddress': typeof AuthenticatedTokenTokenAddressRoute
  '/market': typeof AuthenticatedMarketIndexRoute
  '/nft': typeof AuthenticatedNftIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/trenches': typeof AuthenticatedTrenchesIndexRoute
  '/trending': typeof AuthenticatedTrendingIndexRoute
  '/wallet': typeof AuthenticatedWalletIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/token/$tokenAddress': typeof AuthenticatedTokenTokenAddressRoute
  '/_authenticated/market/': typeof AuthenticatedMarketIndexRoute
  '/_authenticated/nft/': typeof AuthenticatedNftIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/trenches/': typeof AuthenticatedTrenchesIndexRoute
  '/_authenticated/trending/': typeof AuthenticatedTrendingIndexRoute
  '/_authenticated/wallet/': typeof AuthenticatedWalletIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/token/$tokenAddress'
    | '/market/'
    | '/nft/'
    | '/profile/'
    | '/trenches/'
    | '/trending/'
    | '/wallet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/token/$tokenAddress'
    | '/market'
    | '/nft'
    | '/profile'
    | '/trenches'
    | '/trending'
    | '/wallet'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/'
    | '/_authenticated/token/$tokenAddress'
    | '/_authenticated/market/'
    | '/_authenticated/nft/'
    | '/_authenticated/profile/'
    | '/_authenticated/trenches/'
    | '/_authenticated/trending/'
    | '/_authenticated/wallet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/market/': {
      id: '/_authenticated/market/'
      path: '/market'
      fullPath: '/market/'
      preLoaderRoute: typeof AuthenticatedMarketIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nft/': {
      id: '/_authenticated/nft/'
      path: '/nft'
      fullPath: '/nft/'
      preLoaderRoute: typeof AuthenticatedNftIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/token/$tokenAddress': {
      id: '/_authenticated/token/$tokenAddress'
      path: '/token/$tokenAddress'
      fullPath: '/token/$tokenAddress'
      preLoaderRoute: typeof AuthenticatedTokenTokenAddressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trenches/': {
      id: '/_authenticated/trenches/'
      path: '/trenches'
      fullPath: '/trenches/'
      preLoaderRoute: typeof AuthenticatedTrenchesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trending/': {
      id: '/_authenticated/trending/'
      path: '/trending'
      fullPath: '/trending/'
      preLoaderRoute: typeof AuthenticatedTrendingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet/': {
      id: '/_authenticated/wallet/'
      path: '/wallet'
      fullPath: '/wallet/'
      preLoaderRoute: typeof AuthenticatedWalletIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedTokenTokenAddressRoute: typeof AuthenticatedTokenTokenAddressRoute
  AuthenticatedMarketIndexRoute: typeof AuthenticatedMarketIndexRoute
  AuthenticatedNftIndexRoute: typeof AuthenticatedNftIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedTrenchesIndexRoute: typeof AuthenticatedTrenchesIndexRoute
  AuthenticatedTrendingIndexRoute: typeof AuthenticatedTrendingIndexRoute
  AuthenticatedWalletIndexRoute: typeof AuthenticatedWalletIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedTokenTokenAddressRoute: AuthenticatedTokenTokenAddressRoute,
  AuthenticatedMarketIndexRoute: AuthenticatedMarketIndexRoute,
  AuthenticatedNftIndexRoute: AuthenticatedNftIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedTrenchesIndexRoute: AuthenticatedTrenchesIndexRoute,
  AuthenticatedTrendingIndexRoute: AuthenticatedTrendingIndexRoute,
  AuthenticatedWalletIndexRoute: AuthenticatedWalletIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
